### ISSUE TITLE
Update http and use RequestLinePrefix in IndexSlice

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#103]
Update `http` module to 0.15.4 and use `RequestLinePrefix` in `IndexSlice`.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@cfbd0530-47c1-425c-a2e8-0573a4121bb5, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 32' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [f7140134-3180-4c16-ad27-cba4bff61440](https://www.0crat.com/footprint/CT2E6TK9B/f7140134-3180-4c16-ad27-cba4bff61440), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job was finished in 23 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
