### ISSUE TITLE
Remove unused NormalizedProjectName implementation

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#104]
Remove `NormalizedProjectName.FromFilename` class and corresponding test as it's not used anymore (project name is obtained from metadata).

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@cfbd0530-47c1-425c-a2e8-0573a4121bb5, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 32' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [af2a1132-da00-4120-b46a-aebdf1e8c281](https://www.0crat.com/footprint/CT2E6TK9B/af2a1132-da00-4120-b46a-aebdf1e8c281), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job was finished in 23 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
