### ISSUE TITLE
Bump http version

### ISSUE THREAD

**Issue by Sammers21** [artipie/pypi-adapter#109]
Http version should be updated, the current version does not function properly at artipie without it.

**Comment by Sammers21** [comment]
@olegmoz, @olenagerasimova, can you release a new version, please?

**Comment by olegmoz** [comment]
@olenagerasimova could you please release `pypi-adapter`? I am not an architect in `.rultor` here

**Comment by olenagerasimova** [comment]
@olegmoz sure, one moment

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.6.2`
