### ISSUE TITLE
Python proxy

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#126]
Let's add python proxy, do not forget about authorization and integration tests.

- [x]  Index proxy https://github.com/artipie/pypi-adapter/issues/128
- [x] Artifact proxy https://github.com/artipie/pypi-adapter/issues/129
- [x] Proxy auth https://github.com/artipie/pypi-adapter/issues/130

**Comment by olegmoz** [comment]
@olenagerasimova do you think this issue may be finished next week? If not, I'd ask to decompose it into smaller issues: for example basic proxy functionality first, cache next and authentication afterwards.

**Comment by olenagerasimova** [comment]
@olegmoz I've decomposed this issue, I think next week we can finish the first part about index page proxy

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.7`

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#126` is not assigned, can't get performer
