### ISSUE TITLE
Support pip search command

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#135]
Let's support [`pip search`](https://pip.pypa.io/en/stable/reference/pip_search/) as [artifactory](https://www.jfrog.com/confluence/display/JFROG/PyPI+Repositories#PyPIRepositories-SearchingforPyPIPackages) does. We should start with integration test as pip probably makes requests to indexes while searching and search is already working.

On search pip performs `POST` request to the index root with the following body
```html
<?xml version='1.0'?>
<methodCall>
<methodName>search</methodName>
<params>
<param>
<value><struct>
<member>
<name>name</name>
<value><array><data>
<value><string>alarmtime</string></value>
</data></array></value>
</member>
<member>
<name>summary</name>
<value><array><data>
<value><string>alarmtime</string></value>
</data></array></value>
</member>
</struct></value>
</param>
<param>
<value><string>or</string></value>
</param>
</params>
</methodCall>
```

Documentation for `pip search` can be found [here](https://warehouse.readthedocs.io/api-reference/xml-rpc.html).

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.7.1`

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#135` is not assigned, can't get performer

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.7.1`
