### ISSUE TITLE
Save content to cache by normalized key

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#147]
We should save content by normalized keys in proxy cache to avoid caching of the same content twice. For example `https://pypi.org/simple` redirects `/AlarmTime` to `/alarmtime`, so saving content by normalized keys we can provide more reliable proxy.

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.7.2`

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#147` is not assigned, can't get performer
