### ISSUE TITLE
Support absent content in proxy

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#149]
Let's update `asto` and support absent content in proxy by returning 404 to the client.

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#149` is not assigned, can't get performer

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.7.3`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.7.3`
