### ISSUE TITLE
StaticContent.java:92: Extract it into another class

### ISSUE THREAD

**Issue by 0pdd** [artipie/pypi-adapter#30]
The puzzle `28-11c04522` from #28 has to be resolved: 

https://github.com/artipie/pypi-adapter/blob/ae4c915069149ce2212c47b9313c492ee7e1d491/src/main/java/com/artipie/pypi/StaticContent.java#L92-L92

The puzzle was created by @Guseyn on 10-Mar-20. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `28-11c04522` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#30` is not assigned, can't get performer
