### ISSUE TITLE
Codecov errors in CI 

### ISSUE THREAD

**Issue by artemlazarev** [artipie/pypi-adapter#32]
We need to fix Codecov errors in CI process.
There is no ./target/site/jacoco/jacoco.xml file at the filesystem

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#32` is not assigned, can't get performer
