### ISSUE TITLE
PyPi doesn't work

### ISSUE THREAD

**Issue by g4s8** [artipie/pypi-adapter#33]
Fix PyPi adapter and integrate to Artipie.

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by 0crat** [comment]
The job [#33](https://github.com/artipie/pypi-adapter/issues/33) assigned to @artemlazarev[/z](https://www.0crat.com/u/artemlazarev), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/aea6395f-54a2-40a4-91e7-1ce211be30f5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @artemlazarev[/z](https://www.0crat.com/u/artemlazarev) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@artemlazarev[/z](https://www.0crat.com/u/artemlazarev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#41](https://github.com/artipie/pypi-adapter/issues/41), [#42](https://github.com/artipie/pypi-adapter/issues/42) are still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#33` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#68](https://github.com/artipie/pypi-adapter/issues/68) is still not solved; solved: [#41](https://github.com/artipie/pypi-adapter/issues/41), [#42](https://github.com/artipie/pypi-adapter/issues/42).

**Comment by 0pdd** [comment]
@g4s8 all 3 puzzles are solved here: [#41](https://github.com/artipie/pypi-adapter/issues/41), [#42](https://github.com/artipie/pypi-adapter/issues/42), [#68](https://github.com/artipie/pypi-adapter/issues/68).
