### ISSUE TITLE
fix build issues

### ISSUE THREAD

**Issue by artemlazarev** [artipie/pypi-adapter#34]
According project progress "artipie-http" we must fix build issue of our project.
See file StaticContent.java:[73,51].

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@artemlazarev as I can see the build is ok: https://github.com/artipie/pypi-adapter/runs/666501143 where are these build issues?

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#34` is not assigned, can't get performer
