### ISSUE TITLE
Create pypi registery server in tests

### ISSUE THREAD

**Issue by Guseyn** [artipie/pypi-adapter#4]

**Comment by amihaiemil** [comment]
@Guseyn Please add descriptive texts to your Issues, not just titles. What is this issue about? What is missing or broken and how it can be implemented or fixed.

**Comment by Guseyn** [comment]
@amihaiemil would you start working on the task if I will leave a description? Otherwise it's just waste of time as I am the only one who's gonna write the code for this task at least. And more over I am not sure what exactly I am going to do. It's just more a reminder to me.

**Comment by amihaiemil** [comment]
@Guseyn Well, I might work on this project in the future. And many others might work on this project.

And when I start working on an OSS project, the first thing I do is look to see what has been implemented already and what needs to be implemented/fixed further. A well-structured OSS project has discipline as work is being done through tickets/Issues. But if I open Issues and I see nothing else than a superficial title, what will I understand?

Don't just open Issues for yourself "as a reminder". Even if you work on a new Issue, open and describe it as if someone else, new on a project, would have to fix it -- that person needs to understand what the Issue is about.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@4a330cef4d32, thread: pool-240-thread-1
org.hamcrest.MatcherAssert[20] java.lang.AssertionError: HTTP response status is not equal to 205:
202 Accepted [https://api.github.com/notifications]
Date: Sat, 01 Feb 2020 11:11:25 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 132
Server: GitHub.com
Status: 202 Accepted
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4989
X-RateLimit-Reset: 1580559049
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-GitHub-Request-Id: DC38:4606:450425F:527A085:5E355CD5

{"message":"Unread notifications couldn't be marked in a single request. Notifications are being marked as read in the background."}
Expected: HTTP response with status 205
     but: was <202 Accepted [https://api.github.com/notifications]
Date: Sat, 01 Feb 2020 11:11:25 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 132
Server: GitHub.com
Status: 202 Accepted
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4989
X-RateLimit-Reset: 1580559049
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-GitHub-Request-Id: DC38:4606:450425F:527A085:5E355CD5

{"message":"Unread notifications couldn't be marked in a single request. Notifications are being marked as read in the background."}>
```

[0.51.0](https://github.com/zerocracy/farm): Issue: artipie/pypi-adapter#4, Action: `created`

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#4` is not assigned, can't get performer
