### ISSUE TITLE
implement integrational test with big file

### ISSUE THREAD

**Issue by artemlazarev** [artipie/pypi-adapter#40]
Check multipart uploud functionality

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
duplicates #49

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#40` is not assigned, can't get performer
