### ISSUE TITLE
SliceIndex.java:39-41: made implementation of class that...

### ISSUE THREAD

**Issue by 0pdd** [artipie/pypi-adapter#41]
The puzzle `33-be848d82` from #33 has to be resolved: 

https://github.com/artipie/pypi-adapter/blob/8e7ebedc577f76ce95290c8345fcfbed2f984892/src/main/java/com/artipie/pypi/SliceIndex.java#L39-L41

The puzzle was created by @g4s8 on 18-Jun-20. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#41](https://github.com/artipie/pypi-adapter/issues/41) assigned to @artemlazarev[/z](https://www.0crat.com/u/artemlazarev), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/384a0e84-cae9-4831-915a-0da0f31a40f8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @artemlazarev[/z](https://www.0crat.com/u/artemlazarev) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@artemlazarev[/z](https://www.0crat.com/u/artemlazarev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `33-be848d82` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#68](https://github.com/artipie/pypi-adapter/issues/68) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @artemlazarev[/z](https://www.0crat.com/u/artemlazarev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#68](https://github.com/artipie/pypi-adapter/issues/68) is solved here.
