### ISSUE TITLE
HtmlIndexResponse.java:42-44: split {@link...

### ISSUE THREAD

**Issue by 0pdd** [artipie/pypi-adapter#42]
The puzzle `33-99347fb8` from #33 has to be resolved: 

https://github.com/artipie/pypi-adapter/blob/8e7ebedc577f76ce95290c8345fcfbed2f984892/src/main/java/com/artipie/pypi/HtmlIndexResponse.java#L42-L44

The puzzle was created by @g4s8 on 18-Jun-20. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `33-99347fb8` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#42` is not assigned, can't get performer
