### ISSUE TITLE
made integrational test for install operation with "latest" tag

### ISSUE THREAD

**Issue by artemlazarev** [artipie/pypi-adapter#46]
made integrational test for install operation with "latest" tag.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
done in #48

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#46` is not assigned, can't get performer
