### ISSUE TITLE
implement authorization

### ISSUE THREAD

**Issue by artemlazarev** [artipie/pypi-adapter#47]

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by g4s8** [comment]
@rultor release, tag=`0.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.2`
