### ISSUE TITLE
Refactoring use latest code updates from ContentType class

### ISSUE THREAD

**Issue by artemlazarev** [artipie/pypi-adapter#51]
@artemlazarev two comments, please, take a look.
Also I'd suggest updating (maybe in separate issue/PR) http: ContentType class was introduced and other useful changes were made there.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
not valid any more

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#51` is not assigned, can't get performer
