### ISSUE TITLE
Pypi repository doesn't save anything

### ISSUE THREAD

**Issue by g4s8** [artipie/pypi-adapter#54]
When uploading python package to Artipie `pypi` repository using command:
```bash
twine upload --repository-url=https://central.artipie.com/some/location -u <user> -p <pass> dist/*
```
Artipie accepts the payload and client completes successfully, but `tar.gz` packaged from `dist/` doesn't appear on Artipie storage.

**Comment by 0crat** [comment]
The job [#54](https://github.com/artipie/pypi-adapter/issues/54) assigned to @artemlazarev[/z](https://www.0crat.com/u/artemlazarev), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/bafbc170-69bf-44be-a5f0-23e072261686); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @artemlazarev[/z](https://www.0crat.com/u/artemlazarev) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I see that you unassigned this issue; the order is still assigned to @artemlazarev[/z](https://www.0crat.com/u/artemlazarev) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
Job [#54](https://github.com/artipie/pypi-adapter/issues/54) is already in scope

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @artemlazarev[/z](https://www.0crat.com/u/artemlazarev) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
@artemlazarev[/z](https://www.0crat.com/u/artemlazarev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The job [#54](https://github.com/artipie/pypi-adapter/issues/54) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/62026205-6bb0-40a7-9c8d-508065a51e32); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by olenagerasimova** [comment]
@g4s8 I've just upload test project into pypi repository (repository https://central.artipie.com/olenagerasimova/pypi/), can we close it?

**Comment by g4s8** [comment]
@olenagerasimova I just checked, and it's working, thanks
