### ISSUE TITLE
Normalized Names support

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#59]
About valid python project name:
> only valid characters in a name are the ASCII alphabet, ASCII numbers, ., -, and _. The name should be lowercased with all runs of the characters ., -, or _ replaced with a single - character.

According to [PEP 503](https://www.python.org/dev/peps/pep-0503/) simple python repo:
> Repositories MAY redirect unnormalized URLs to the canonical normalized URL (e.g. /Foobar/ may redirect to /foobar/), however clients MUST NOT rely on this redirection and MUST request the normalized URL.

While installing project `pip` 
- normalizes packages names when trying to obtain index page for package
- download package by provided links without normalization

E.g.
```bash
python3 -m pip install -v --index-url http://https://pypi.org/simple --no-deps aav.upcoming_games
1 location(s) to search for versions of aav.upcoming-games:
* https://pypi.org/simple/aav-upcoming-games/
Fetching project page and analyzing links: https://pypi.org/simple/aav-upcoming-games/
...
Starting new HTTPS connection (1): files.pythonhosted.org:443
  https://files.pythonhosted.org:443 "GET /packages/58/78/afc4cdffa533d3bd1d26df64e6dcf0ab17d96f4c1090f84ba10de9eafda6/aav.upcoming_games-0.1.0-py3-none-any.whl HTTP/1.1" 200 7622
  Downloading aav.upcoming_games-0.1.0-py3-none-any.whl (7.6 kB)
...
```

Python test [repository](https://pypi.org/simple/) redirects indexes to normalized urls, for example
```bash
curl -v https://pypi.org/simple/aav.upcoming.games/
GET /simple/aav.upcoming.games/ HTTP/2
< HTTP/2 301 
< content-type: text/html; charset=UTF-8
< location: https://pypi.org/simple/aav-upcoming-games/
< content-length: 224
< 
<html>
 <head>
  <title>301 Moved Permanently</title>
 </head>
 <body>
  <h1>301 Moved Permanently</h1>
  The resource has been moved to /simple/aav-upcoming-games/; you should be redirected automatically.
 </body>
</html>
```

So, I think we should 
1. normalize package name while adding artifact into storage, use this normalized name as a directory key and leave file name as is, e.g. file `Alarm_Time-0.3.tar.gz` should be stored by key `alarm-time/Alarm_Time-0.3.tar.gz`
2. redirect unnormalized names: `/Alarm_Time` to `/alarm_time`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@bb368ec0-5f42-44b8-acc9-d78097fdae6e, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 30' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [79ed4647-96b5-40dc-a62a-a91eee9e4a1e](https://www.0crat.com/footprint/CT2E6TK9B/79ed4647-96b5-40dc-a62a-a91eee9e4a1e), Type: "Job milestoned"

**Comment by olenagerasimova** [comment]
@g4s8 could you please take a look? Do you agree with my suggestion?

**Comment by g4s8** [comment]
@olenagerasimova yes, I agree, let's normalize package names and redirect unnormalized names.

**Comment by olenagerasimova** [comment]
@g4s8 I've extracted redirect support to #79 as this feature it not as relevant and urgent as names normalization.

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.5.1`

**Comment by olenagerasimova** [comment]
done in #78 and will be done in #79

**Comment by 0crat** [comment]
Job was finished in 12 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
