### ISSUE TITLE
IT case to publish and install python package

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#61]
Create IT case to first publish and then install python. After the installation verify that package works properly.

**Comment by olenagerasimova** [comment]
done in #71

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.4`

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#61` is not assigned, can't get performer

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.4`
