### ISSUE TITLE
Add code coverage metrics

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#63]
Use jacoco plugin and codecov to set up code coverage metrics.

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#67](https://github.com/artipie/pypi-adapter/issues/67) is still not solved.

**Comment by olenagerasimova** [comment]
done in #64

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#63` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@olenagerasimova the only puzzle [#67](https://github.com/artipie/pypi-adapter/issues/67) is solved here.
