### ISSUE TITLE
pom.xml:168-171: Improve code coverage by writing...

### ISSUE THREAD

**Issue by 0pdd** [artipie/pypi-adapter#67]
The puzzle `63-ecd3feaa` from #63 has to be resolved: 

https://github.com/artipie/pypi-adapter/blob/718f74b5d0ba312e32a900594f2cbc2dc3ca45b8/pom.xml#L168-L171

The puzzle was created by @olenagerasimova on 13-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by olenagerasimova** [comment]
@0crat in

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) I see that you unassigned this issue; the order is still assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0pdd** [comment]
The puzzle `63-ecd3feaa` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@20024866-699c-4c88-8b9d-87fc1cdf687f, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 31' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [3383c3ce-a629-403f-a20d-2c19d907f4ec](https://www.0crat.com/footprint/CT2E6TK9B/3383c3ce-a629-403f-a20d-2c19d907f4ec), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job was finished in 8 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
