### ISSUE TITLE
SliceIndexTest.java:40-41: Extend this test: check...

### ISSUE THREAD

**Issue by 0pdd** [artipie/pypi-adapter#68]
The puzzle `41-22a137cd` from #41 has to be resolved: 

https://github.com/artipie/pypi-adapter/blob/9953c68d12a681e84996f74261060ecf98302433/src/test/java/com/artipie/pypi/http/SliceIndexTest.java#L40-L41

The puzzle was created by @olenagerasimova on 13-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@349556e6-fa72-4cfa-be64-c068e2ccb4e1, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 29' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [a4a2d2c6-a407-4bbe-afad-8901d3e1f6d9](https://www.0crat.com/footprint/CT2E6TK9B/a4a2d2c6-a407-4bbe-afad-8901d3e1f6d9), Type: "Job milestoned"

**Comment by 0pdd** [comment]
The puzzle `41-22a137cd` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 8 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
