### ISSUE TITLE
`WheelSlice` looses path from request

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#74]
`WheelSlice` looses key part from request on save: if request line is `\sample` and filename is `myproject-0.0.1.whl` then file should be saved by `sample\myproject\myproject-0.0.1.whl` key instead of `myproject\myproject-0.0.1.whl`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@0669e23f-3c63-4d1b-903b-771d227143c3, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 29' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [7ba1eaa5-2043-42dc-b945-c8f92b85e0d9](https://www.0crat.com/footprint/CT2E6TK9B/7ba1eaa5-2043-42dc-b945-c8f92b85e0d9), Type: "Job milestoned"

**Comment by olenagerasimova** [comment]
done in #75

**Comment by 0crat** [comment]
Job was finished in 14 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
