### ISSUE TITLE
Redirect to normalized project names support 

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#79]
According to [PEP 503](https://www.python.org/dev/peps/pep-0503/#specification) simple python repo:

> Repositories MAY redirect unnormalized URLs to the canonical normalized URL (e.g. /Foobar/ may redirect to /foobar/), however clients MUST NOT rely on this redirection and MUST request the normalized URL.

We should support this feature by introducing redirect slice. This slice should normalize last part of the request line and redirect to the new location.  
More details can be found in #59.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@18b2b518-edf9-422f-9f93-db5644685e7d, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 30' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [f9dfc930-e07c-4ed4-8c74-cd988721c776](https://www.0crat.com/footprint/CT2E6TK9B/f9dfc930-e07c-4ed4-8c74-cd988721c776), Type: "Job milestoned"

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.5.2`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.5.2`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.5.2`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.5.3`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.5.4`
