### ISSUE TITLE
Integration test with denormalized project name

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#82]
Add integration test with denormalized python project name.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@18b2b518-edf9-422f-9f93-db5644685e7d, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 30' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [4b894eec-c9dc-4d8a-8d8e-003da398f03c](https://www.0crat.com/footprint/CT2E6TK9B/4b894eec-c9dc-4d8a-8d8e-003da398f03c), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job was finished in 27 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
