### ISSUE TITLE
Read project metadata file on upload

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#86]
Python project name should be obtained from project archive on upload by unpacking the archive and reading project metadata file. Package format is described by [PEP 427](https://www.python.org/dev/peps/pep-0427/)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@2c195277-118e-4273-9270-2831e5de3be2, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 31' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [d59fff6e-8f99-4307-8ea9-04b00a9ea470](https://www.0crat.com/footprint/CT2E6TK9B/d59fff6e-8f99-4307-8ea9-04b00a9ea470), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#86` is not assigned, can't get performer
