### ISSUE TITLE
Update asto to 0.23.3

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#88]
Update asto to 0.23.3 and use `KeyLastPart` and `PublisherAs` from the new version.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@bcf4c1ce-a1bb-461a-bc3c-b71f9064f293, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 31' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [0186fa7e-ad85-48c9-830f-e94cafdc3461](https://www.0crat.com/footprint/CT2E6TK9B/0186fa7e-ad85-48c9-830f-e94cafdc3461), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job was finished in 5 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
