### ISSUE TITLE
Support all possible source distributions formats on download

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#92]
Python `sdist` [supports](https://docs.python.org/2/distutils/sourcedist.html) various source distribution archive formats: `zip`, `tar.gz`, `tar.bz2`, `tar.Z` and `.tar`. For now upload works for any file formats, but download works only for `whl` and `tar.gz`. This should be fixed.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@20024866-699c-4c88-8b9d-87fc1cdf687f, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 31' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [d084f8ff-9994-4353-88e3-ad030731b824](https://www.0crat.com/footprint/CT2E6TK9B/d084f8ff-9994-4353-88e3-ad030731b824), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job [#92](https://github.com/artipie/pypi-adapter/issues/92) is not in the agenda of @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), can't set title

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
