### ISSUE TITLE
Support python .egg packages

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#96]
Let's support legacy `egg` packages:

> Egg is a built distribution format introduced by setuptools, which is being replaced by Wheel

For more information check the [glossary](https://packaging.python.org/glossary/#term-egg) and [internal structure](https://setuptools.readthedocs.io/en/latest/formats.html).

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@964e303f-91b1-49ab-afed-1b886adbfcd3, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 32' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [40a2404f-6b16-4ae1-8def-79b3c72f0812](https://www.0crat.com/footprint/CT2E6TK9B/40a2404f-6b16-4ae1-8def-79b3c72f0812), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#96` is not assigned, can't get performer
