### ISSUE TITLE
Support tar.Z and tar.bz2

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/pypi-adapter#99]
Let's support `tar.bz2` and `tar.Z` archives upload as they are officially supported by [sdist](https://docs.python.org/3/distutils/sourcedist.html).

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@964e303f-91b1-49ab-afed-1b886adbfcd3, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 32' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [41d5c979-d726-4cff-ad2a-95f9c1fec701](https://www.0crat.com/footprint/CT2E6TK9B/41d5c979-d726-4cff-ad2a-95f9c1fec701), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job was finished in 7 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.6`
